"""empty message

Revision ID: 379777cf7f7d
Revises: f26b3dbf66a2
Create Date: 2024-04-23 12:21:43.269597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379777cf7f7d'
down_revision = 'f26b3dbf66a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
