"""empty message

Revision ID: 59344485de26
Revises: 379777cf7f7d
Create Date: 2024-04-23 12:44:20.009084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59344485de26'
down_revision = '379777cf7f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
