"""empty message

Revision ID: dcc6dfa2b416
Revises: 646f5a7c5f0a
Create Date: 2024-04-24 11:30:08.541241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc6dfa2b416'
down_revision = '646f5a7c5f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completion', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
